// <auto-generated />
using DatabaseEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseEF.Migrations
{
    [DbContext(typeof(KanbanContext))]
    [Migration("20181217065822_TestingStuffFifth")]
    partial class TestingStuffFifth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DatabaseEF.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("TaskID");

                    b.HasKey("ID");

                    b.HasIndex("TaskID")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("DatabaseEF.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PersonOnItID");

                    b.HasKey("ID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DatabaseEF.Person", b =>
                {
                    b.HasOne("DatabaseEF.Task", "Task")
                        .WithOne("PersonOnIt")
                        .HasForeignKey("DatabaseEF.Person", "TaskID");
                });
#pragma warning restore 612, 618
        }
    }
}
